---
packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - software-properties-common
  - git
  - wget
  - unzip
  - ruby-full
  - python3-pip
  
java_home: "/usr/lib/jvm/java-{{ java_version }}-openjdk-amd64"

