workspace_user: "jenkins"
workspace_group: "jenkins"
workspace_root: "/home/jenkins"
flutter_version: "stable"
java_version: "17"
fastlane_version: "latest"
android_sdk_version: "33"
android_build_tools_version: "33.0.0"
flutter_path: "{{ workspace_root }}/flutter"
android_sdk_path: "{{ workspace_root }}/android-sdk"

